language: ruby
sudo: required
git:
  depth: 9999
branches:
  except:
    - "/^[0-9]/"
services:
  - docker
before_install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      echo "Do not open PRs against master; merge dev into master locally and push instead."
      exit 1
    fi
  - export DOCKER_IMAGE_TAG=b0ee759983428699935bf7a7e30d98ab690819a9
  - export ARTIFACT_VERSION=$(git rev-list --count HEAD)
  - export TERM=dumb
  - openssl aes-256-cbc -K $encrypted_13d4b12ffe60_key -iv $encrypted_13d4b12ffe60_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - docker pull stoyicker/docker-android:${DOCKER_IMAGE_TAG}
  - docker tag stoyicker/docker-android:${DOCKER_IMAGE_TAG} stoyicker/docker-android
  - export CONTAINER=$(docker run -dt -p 127.0.0.1:80:4567 -e ARTIFACT_VERSION -e TERM -e TRAVIS_BRANCH -e REPO_USER -e GITHUB_TOKEN -e TRAVIS_REPO_SLUG stoyicker/docker-android)
  - docker exec -t $CONTAINER /bin/sh -c "mkdir -p /root/${TRAVIS_REPO_SLUG}"
  - docker cp ./ $CONTAINER:root/${TRAVIS_REPO_SLUG}
env:
  matrix:
  - TASK="\"./gradlew :app:build --no-daemon\""
  - TASK="\"./gradlew :data:build --no-daemon\""
  - TASK="\"./gradlew :proxy-data:build --no-daemon\""
  - TASK="\"./gradlew :domain:build --no-daemon\""
  - TASK="\"./gradlew :views:build --no-daemon\""
  - TASK="\"./gradlew :extensions:build --no-daemon\""
  - TASK="\"./gradlew :crash-reporter:build --no-daemon\""
  - TASK="\"./gradlew :event-tracker:build --no-daemon\""
script:
  - docker exec -it $CONTAINER /bin/sh -c "cd root/${TRAVIS_REPO_SLUG}; ./_ci/script.sh ${TASK}"
after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ] && [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then
      echo "CI on master succeded. Executing release tasks..."
      docker exec -t $CONTAINER /bin/sh -c "cd root/${TRAVIS_REPO_SLUG}; ./_ci/release.sh"
    fi
notifications:
  email: false
